# Generated by Django 5.2.7 on 2025-10-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draft', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget', models.FloatField()),
                ('draft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.draft')),
                ('draft_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.draftuser')),
            ],
        ),
    ]
