# Generated by Django 5.2.7 on 2025-10-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='draft_id',
            new_name='draft',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='draft_user_id',
            new_name='draft_user',
        ),
    ]
