# Generated by Django 5.2.7 on 2025-10-11 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='draft_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.draftuser'),
        ),
    ]
