# Generated by Django 5.2.7 on 2025-10-11 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1)),
                ('position', models.CharField(choices=[('GL', 'Portero'), ('DF', 'Defensa'), ('MF', 'Centrocampista'), ('FW', 'Delantero')], max_length=2)),
                ('element', models.CharField(choices=[('air', 'Aire'), ('fire', 'Fuego'), ('earth', 'Montaña'), ('wood', 'Bosque')], max_length=5)),
                ('sprite', models.ImageField(blank=True, null=True, upload_to='imgs/')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='DraftPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('release_clause', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='draft.draft')),
            ],
        ),
    ]
