# Generated by Django 5.2.7 on 2025-10-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=50)),
                ('element', models.CharField(max_length=50)),
                ('sprite', models.URLField(blank=True)),
                ('team_id', models.IntegerField()),
                ('techniques', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=50)),
                ('element', models.CharField(max_length=50)),
                ('sprite', models.URLField(blank=True)),
                ('game_team', models.CharField(max_length=100)),
                ('team_sprite', models.URLField(blank=True)),
            ],
        ),
    ]
