# Generated by Django 5.2.7 on 2025-10-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftplayer',
            name='element',
        ),
        migrations.RemoveField(
            model_name='draftplayer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='draftplayer',
            name='position',
        ),
        migrations.RemoveField(
            model_name='draftplayer',
            name='sprite',
        ),
        migrations.RemoveField(
            model_name='draftplayer',
            name='techniques',
        ),
        migrations.RemoveField(
            model_name='player',
            name='game_team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team_sprite',
        ),
        migrations.AddField(
            model_name='draftplayer',
            name='draft_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='draft.draft'),
        ),
        migrations.AddField(
            model_name='draftplayer',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='draftplayer',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='element',
            field=models.CharField(choices=[('air', 'Aire'), ('fire', 'Fuego'), ('earth', 'Montaña'), ('wood', 'Bosque')], max_length=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GL', 'Portero'), ('DF', 'Defensa'), ('MF', 'Centrocampista'), ('FW', 'Delantero')], max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='sprite',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
