# Generated by Django 5.2.7 on 2025-10-10 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_draftplayer_element_remove_draftplayer_gender_and_more'),
        ('team', '0002_rename_draft_id_team_draft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftplayer',
            old_name='draft_id',
            new_name='draft',
        ),
        migrations.RenameField(
            model_name='draftplayer',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RemoveField(
            model_name='draftplayer',
            name='order',
        ),
        migrations.RemoveField(
            model_name='draftplayer',
            name='team_id',
        ),
        migrations.AddField(
            model_name='draftplayer',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team'),
        ),
    ]
