# Generated by Django 5.2.7 on 2025-10-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftplayer',
            name='value',
        ),
    ]
