# Generated by Django 5.2.7 on 2025-10-10 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
        ('users', '0003_rename_draft_id_draftuser_draft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='league_id',
            new_name='league',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='current_draft_player_id',
        ),
        migrations.AddField(
            model_name='draft',
            name='current_draft_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_draft', to='users.draftuser'),
        ),
    ]
