# Generated by Django 5.2.7 on 2025-10-21 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draft', '0002_initial'),
        ('players', '0003_remove_draftplayer_value'),
        ('team', '0003_team_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('local_goals', models.IntegerField(blank=True, null=True)),
                ('away_goals', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Nuevo'), ('pending_result', 'Pendiente de resultado'), ('finished', 'En curso')], default='pending', max_length=100)),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_team', to='team.team')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.draft')),
                ('local_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_team', to='team.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='team.team')),
            ],
        ),
        migrations.CreateModel(
            name='GameResultRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_goals', models.IntegerField(blank=True, null=True)),
                ('away_goals', models.IntegerField(blank=True, null=True)),
                ('goals', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Nuevo'), ('aprobada', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=100)),
                ('away_goalkeeper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_goalkeeper', to='players.draftplayer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('local_goalkeeper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_goalkeeper', to='players.draftplayer')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('draft_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.draftplayer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
