# Generated by Django 5.2.7 on 2025-10-10 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
        ('users', '0003_rename_draft_id_draftuser_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_leagues', to='users.user'),
        ),
    ]
