# Generated by Django 5.2.7 on 2025-10-11 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='draftuser',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='draft.draft'),
        ),
        migrations.AlterField(
            model_name='draftuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='draftuser',
            index=models.Index(fields=['draft'], name='users_draft_draft_i_1d8416_idx'),
        ),
        migrations.AddIndex(
            model_name='draftuser',
            index=models.Index(fields=['user'], name='users_draft_user_id_62c23e_idx'),
        ),
        migrations.AddConstraint(
            model_name='draftuser',
            constraint=models.UniqueConstraint(fields=('draft', 'user'), name='unique_user_in_draft'),
        ),
    ]
