# Generated by Django 5.2.7 on 2025-10-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_key_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftuser',
            old_name='draft_id',
            new_name='draft',
        ),
        migrations.RenameField(
            model_name='draftuser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='draftuser',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
