# Generated by Django 5.2.7 on 2025-10-11 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_initial'),
        ('users', '0002_remove_draftuser_username_alter_draftuser_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftuser',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.draft'),
        ),
        migrations.AlterField(
            model_name='draftuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
